### ISSUE TITLE
add metadata-links.csv to trigger creation of new observatory-{id}-data repositories

### ISSUE THREAD

**Issue by marc-portier** [emo-bon/governance-data#12]
To automate the creation of separate sampling-repositories form the managed sampling data on google-sheets we are going to provide a github action.

To feed its working though we need a list `metadata-links.csv` of the URLs to the created google-sheets 
A first version of this file has been provided (converted to utf-8 to safeguard international chars) --> [EMO_BON_metadata_links.csv](https://github.com/emo-bon/governance-data/files/10091591/EMO_BON_metadata_links.csv)  

To be useful though it misses a column "EMOBON_observatory_id" that matches the code assigned to each observatory (as listed in observatories.csv

@isanti could you help in adding the missing column?

**Comment by isanti** [comment]
[EMO_BON_metadata_links.csv](https://github.com/emo-bon/governance-data/files/10120503/EMO_BON_metadata_links.csv)
Here is the file EMO_BON_metadata_links.csv updated to include the observatory id. It also includes a new observatory (UmU) that was recently added (new raw). I haven't converted it to utf-8 because I wasn't sure how.

**Comment by isanti** [comment]
[EMO_BON_metadata_links.csv](https://github.com/emo-bon/governance-data/files/10120689/EMO_BON_metadata_links.csv)
Same file but using comma (,) as separator instead of semicolon.
